codecov:
  token: 7fe199ac-ee2b-4a80-b21f-17a9c37af37d
ignore:
  - "Pyrado/doc"
  - "Pyrado/pyrado/environments/barrett_wam"
  - "Pyrado/pyrado/environments/mujoco"
  - "Pyrado/scripts"
  - "Pyrado/tests"
